-- --------------------------------------------------------
-- Host:                         localhost
-- Versión del servidor:         5.7.24 - MySQL Community Server (GPL)
-- SO del servidor:              Win64
-- HeidiSQL Versión:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando datos para la tabla ambiental.categories: ~7 rows (aproximadamente)
/*!40000 ALTER TABLE `categories` DISABLE KEYS */;
INSERT INTO `categories` (`id`, `name`, `created_at`, `updated_at`) VALUES
	(5, 'ORGANIZACIONES', '2020-12-02 06:09:50', '2020-12-02 06:09:50'),
	(6, 'HÁBITOS NEGATIVOS', '2020-12-02 06:15:12', '2020-12-02 06:18:55'),
	(7, 'HÁBITOS POSITIVOS', '2020-12-02 06:19:08', '2020-12-02 06:19:08'),
	(8, 'CUIDADO', '2020-12-02 06:59:05', '2020-12-02 06:59:05'),
	(9, 'IMPORTANCIA', '2020-12-02 07:02:55', '2020-12-02 07:02:55'),
	(10, 'CUIDADO', '2020-12-02 07:04:21', '2020-12-02 07:04:21'),
	(11, 'DEFINICION', '2020-12-02 07:07:47', '2020-12-02 07:07:47');
/*!40000 ALTER TABLE `categories` ENABLE KEYS */;

-- Volcando datos para la tabla ambiental.failed_jobs: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `failed_jobs` DISABLE KEYS */;
/*!40000 ALTER TABLE `failed_jobs` ENABLE KEYS */;

-- Volcando datos para la tabla ambiental.migrations: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2019_08_19_000000_create_failed_jobs_table', 1),
	(4, '2019_12_09_212855_create_categories_table', 1),
	(5, '2019_12_09_213159_create_posts_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Volcando datos para la tabla ambiental.password_resets: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- Volcando datos para la tabla ambiental.posts: ~7 rows (aproximadamente)
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` (`id`, `user_id`, `category_id`, `title`, `slug`, `body`, `image`, `created_at`, `updated_at`) VALUES
	(5, 1, 5, 'ORGANIZACIONES QUE PROTEGEN EL MEDIO AMBIENTE', 'organizaciones-que-protegen-el-medio-ambiente', 'Existen instituciones u organizaciones que protegen el medio ambiente en la Tierra, cuyo objetivo común es la conservación del patrimonio natural ambiental del planeta. Pueden ser organizaciones internacionales o locales, la mayoría de las cuales son organizaciones no gubernamentales (ONG´s), sin fines de lucro.\r\nSus intereses básicos son el estudio y la divulgación de información sobre la importancia de la preservación del ambiente, la reducción de la contaminación ambiental, la conservación de la biodiversidad y el establecimiento de áreas especiales protegidas.\r\n\r\nTENEMOS : GREENPEACE\r\nEl nombre de esta organización proviene del inglés, green: verde y peace: paz. Es una organización no gubernamental que fue fundada en Vancouver, Canadá, en 1971. Define su objetivo como la protección del medio ambiente y la paz mundial.\r\n\r\nEs una de las mayores organizaciones ambientalistas independientes del planeta; posee oficinas nacionales e internacionales en 55 países y 32 millones de afiliados que financian todas sus actividades, además de artistas e intelectuales que recaudan fondos como donaciones. Su sede se encuentra en Ámsterdam, Países Bajos ; WORLD WILDLIFE FUND (WWF)\r\nEl nombre de la organización se traduce al español como Fondo Mundial para la Vida Salvaje, pero se emplea el nombre Fondo Mundial para la Naturaleza. Fue fundada en 1961.\r\nEs la mayor organización no gubernamental ambientalista del planeta. Funciona en más de 100 países a través de unos 5 millones de voluntarios. Su sede se encuentra en Suiza.\r\nSus objetivos de trabajo son la investigación, la conservación y la restauración ambiental, los cuales plantea a través de la conservación de la diversidad biológica del planeta, la promoción del uso sostenible de los recursos ambientales y de la disminución de la contaminación ambiental y el consumo voraz.\r\n\r\n ', 'http://localhost/blog6/public/imagenes/posts/tErTDAfqRkHAgJVJAHGbreE2SRkJBLbASyZOhrqw.jpeg', '2020-12-02 06:11:04', '2020-12-02 06:12:55'),
	(6, 1, 6, 'HÁBITOS COTIDIANOS QUE DAÑAN EL MEDIO AMBIENTE', 'habitos-cotidianos-que-danan-el-medio-ambiente', '1. FUMAR\r\nEl tabaco causa la muerte de cientos de miles de personas en todo el mundo y provoca considerables impactos ambientales: contaminación, pérdida de biodiversidad, incendios forestales, deforestación de bosques y selvas, aumento del cambio climático, etc. Especialmente preocupantes son las consecuencias de las colillas: son el principal residuo recogido en el medio ambiente mundial, con millones de kilos diseminados por todo el planeta. Ningún otro producto de consumo masivo causa tanto daño desde su cultivo, producción, uso y desecho como el tabaco, según la Organización Mundial de la Salud (OMS).\r\nPor tanto, dejar de fumar salva vidas y evita daños ambientes. Y si no se abandona dicho hábito, resulta esencial no arrojar las colillas al entorno, ya sea natural o urbano, ni tampoco al inodoro ; 2. IR EN COCHE PARA TODO\r\nEl 94% de los españoles respira un aire con elementos contaminantes que superan los límites recomendados por la Organización Mundial de la Salud (OMS), según un informe de Ecologistas en Acción. La polución causa más de 400.000 muertes prematuras en Europa cada año y su principal responsable son las emisiones del tráfico urbano, concluyen los informes más recientes de la Agencia Europea de Medio Ambiente (AEMA).\r\n\r\nLos ciudadanos pueden usar y reclamar una movilidad más sostenible: viajar en transporte público, ir a pie o en bicicleta y combinar cualquiera de dichos sistemas. Y si no queda otra que emplear el vehículo privado, elegir un modelo menos contaminante, realizar una conducción eficiente o compartirlo con otras personas.', 'http://localhost/blog6/public/imagenes/posts/CfZ6sjg1kWbCqM9AaJYegKfhU9Q0IFzSeJFCbHPa.jpeg', '2020-12-02 06:16:48', '2020-12-02 06:18:10'),
	(7, 1, 7, 'HÁBITOS COTIDIANOS  QUE MEJORAN AL MEDIO AMBIENTE', 'habitos-cotidianos-que-mejoran-al-medio-ambiente', '1- CONSUMIR ALIMENTOS CON ACEITE DE PALMA\r\n\r\nEl aceite de palma se utiliza en gran cantidad de alimentos. Su consumo no es recomendable para la salud por su alto contenido en grasas saturadas, ni tampoco para el medio ambiente. Su cultivo intensivo en Indonesia o Malasia ha destruido grandes bosques tropicales, ha puesto en peligro de extinción a gran cantidad de especies, como el orangután, ha incrementado las emisiones de gases de efecto invernadero (GEI), implicadas en el cambio climático, y ha dañado los hábitats de las zonas de cultivo.\r\nLos consumidores pueden evitar estos productos fijándose en la información de sus etiquetas y buscando otras alternativas, preguntar en caso de duda y reclamar productos que no lo empleen. 2-DEPOSITAR TODA LA BASURA DOMÉSTICA EN UNA SOLA BOLSA\r\nSeparar los residuos domésticos y depositarlos en su contenedor para su posterior reciclado puede parecer un esfuerzo inútil, si no se conocen sus beneficios ambientales. Cada vez que se recicla, se evita llenar los vertederos y la extracción de nuevas materias primas, además de reducir el consumo de energía y la emisión de GEI. Una vez que los ciudadanos tienen claro cómo reciclar bien, se convierte en un hábito diario sencillo de realizar.\r\n\r\n ', 'http://localhost/blog6/public/imagenes/posts/9YnmIKiS0XSIDhSDGgOlZ7CJzvYiTnrB16A2L1Z0.jpeg', '2020-12-02 06:21:41', '2020-12-02 06:21:41'),
	(8, 1, 8, 'FORMAS DE CUIDAR EL MEDIO AMBIENTE', 'formas-de-cuidar-el-medio-ambiente', '1-AHORRA AGUA: Lavar tu auto con un balde, hacer uso responsable de la lavadora y el lavatrastos, son acciones que ayudarán a reducir significativamente el consumo de este líquido en tu hogar. 2-	DISMINUYE TU CONSUMO DE ELECTRICIDAD\r\nMinimiza el consumo de electricidad aprovechando el consumo de la luz con los cambios de horario. Otra buena idea es cambiar los focos por lámparas led que además de ser un gran ahorro económico cuentan con una alta eficiencia en iluminación. 3-	EVITA EL USO EXCESIVO DEL AUTO\r\nViajar en bicicleta o en transporte público te volverá una persona más activa y contribuirás a contaminar menos. 4-	PLANTA UN ÁRBOL\r\nDebemos encargarnos de llenar los espacios de árboles y plantas, hay que recordar que son ellos los que limpian el aire que respiramos.5-	FOMENTA LA SEPARACIÓN DE BASURA EN TU HOGAR\r\nLos desechos orgánicos pueden funcionar como abono. Algunos plásticos y vidrios pueden reutilizarse, la ropa que ya no usas puede servir a otras personas, etc. Como ves, con estas pequeñas acciones podemos lograr grandes cambios, pero para ello es necesario empezar por un cambio de actitud y de hábitos en nosotros mismos.', 'http://localhost/blog6/public/imagenes/posts/6Z9aXg7k7USfiwKFknv8b8O5zAHgodlarLnLmcFy.jpeg', '2020-12-02 07:01:16', '2020-12-02 07:01:16'),
	(9, 1, 9, 'IMPORTANCIA DEL MEDIO AMBIENTE', 'importancia-del-medio-ambiente', 'Es muy importante ya que es la fuente de la que el ser humano y el resto de los seres vivos obtienen vida. Todos los organismos obtienen del medio el aire y el agua que necesitan para vivir, la energía y el alimento. Mantener el equilibrio del medio ambiente es fundamental para mantener la vida en la Tierra tal como la conocemos. Por eso el hombre debe conocer y cuidar sus interacciones con el medio ambiente para gestionar de manera sostenible los recursos naturales que permiten el crecimiento económico y el desarrollo del ser humano. \r\nPor lo consiguiente, si el medio ambiente es nuestra casa, ¿porque lo estamos destruyendo? el nos brinda todos los recursos indispensables para la continuidad de la vida en el planeta. Es nuestra casa, cuidemos y conservemos de ella no solo por nosotros, sino por nuestros hijos y nietos que merecen vivir en mundo mejor. Demostrémosle la importancia que el se merece para nosotros los humanos', 'http://localhost/blog6/public/imagenes/posts/Op6lDmMm3fE2LlcU2GuNBVhYfaHpqSjckU3LDTgx.jpeg', '2020-12-02 07:03:48', '2020-12-02 07:03:48'),
	(10, 1, 8, 'CUIDADO DEL MEDIO AMBIENTE', 'cuidado-del-medio-ambiente', 'El medio ambiente es el espacio en el que se desarrolla la vida de los organismos y que permite su interacción. Está conformado por seres vivos (factores bióticos), por elementos sin vida (factores abióticos) y por elementos artificiales creados por el hombre. Cuando se habla de seres vivos se hace referencia a la flora, la fauna y los seres humanos; por su parte, los factores abióticos son aquellos que carecen de vida como el aire, el suelo y el agua (elementos que resultan esenciales para la subsistencia de los organismos vivos).', 'http://localhost/blog6/public/imagenes/posts/ZY368PPzJvDJ4JojJt2SuAdCbcX5Dst2daZatRHJ.jpeg', '2020-12-02 07:05:02', '2020-12-02 07:05:02'),
	(11, 1, 11, 'QUE ES MEDIO AMBIENTE', 'que-es-medio-ambiente', 'l medio ambiente es un conjunto equilibrado de elementos que engloba la naturaleza, la vida, los elementos artificiales, la sociedad y la cultura que existen en un espacio y tiempo determinado.\r\n\r\nEl medio ambiente está conformado por diversos componentes como son los físicos, los químicos y los biológicos, así como, los sociales y los culturales. Estos componentes, tangibles e intangibles, se encuentran relacionan unos con otros y establecen las características y el desarrollo de la vida de un lugar.\r\n\r\nEjemplos de estos factores son los animales, las plantas, los seres humanos, el suelo, el aire, el agua, el clima, la geología, las expresiones culturales, las relaciones sociales y económicas, la ocupación laboral, el urbanismo, los enfrentamientos armados, entre otros.\r\n\r\nEl ser humano es el ser vivo que más interviene en el medio ambiente, ya que lo explora, lo modifica y hace uso de sus recursos a fin de alcanzar su bienestar general.\r\n\r\nSin embargo, la actividad humana ha afecto de manera negativa el medio ambiente, se agotan sus recursos naturales, se extinguen la flora y fauna, la industrialización ha aumentado los niveles de contaminación ambiental, el crecimiento demográfico es continuo y los recursos naturales se consumen de manera desmedida.', 'http://localhost/blog6/public/imagenes/posts/xt8BAY4x4IBxHtIIjrI5jkKWeD4aoDTJBWkYePWO.jpeg', '2020-12-02 07:09:22', '2020-12-02 07:09:22');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;

-- Volcando datos para la tabla ambiental.users: ~1 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'maria', 'mariayarleque14@gmail.com', NULL, '$2y$10$g3eowCWJ3a.r26peE7geW.TGcziYxd/mU/44UXWK4bQvjH0ylAVjq', NULL, '2020-12-02 04:00:14', '2020-12-02 04:00:14');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
